qubit_colors = {
    'H1Q1' : 'darkslateblue',
    'H1Q2' : 'seagreen',
    'H2Q1' : 'steelblue',
    'H2Q2' : 'sandybrown',
    'H2Q3' : 'indianred',
    'H3Q1' : 'mediumaquamarine',
    'H3Q2' : 'xkcd:sapphire',
    'H3Q3' : 'xkcd:reddish purple',
    'Waymar1Q1' : 'olivedrab',
    'Waymar1Q2' : 'darkcyan',
    'Waymar1Q3' : 'rebeccapurple',
    'Waymar2Q1' : 'xkcd:barbie pink',
    'Waymar2Q2' : 'xkcd:tangerine',
    'Waymar2Q3' : 'xkcd:barney purple',
    'Waymar2Q4' : 'xkcd:perrywinkle',
    'Waymar2Q5' : 'xkcd:fresh green',
    'MCMC' : 'gold',
}