# -*- coding: utf-8 -*-
#
# pysmurf documentation build configuration file, created by
# sphinx-quickstart on Tue Feb 19 15:17:07 2019.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
# used for source code link resolution
import inspect
import sys
import re
from os.path import dirname, relpath

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
from pysmurf import __file__ as pysmurf_file
from pysmurf import __version__ as pysmurf_version
sys.path.insert(0, os.path.abspath('..'))

pysmurf_git_tag = re.sub('^v', '', os.popen('git describe --tags').read().strip())

# -- Project information -----------------------------------------------------
# General information about the project.
project = u'pysmurf'
copyright = u'2019, The Board of Trustees of the Leland Stanford Junior University, through SLAC National Accelerator Laboratory (subject to receipt of any required approvals from the U.S. Dept. of Energy).'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = pysmurf_version
# The full version, including alpha/beta/rc tags.
release = pysmurf_version

# -- General configuration -----------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.todo',
    'sphinx.ext.linkcode',
    'sphinx.ext.intersphinx',
    'sphinx_copybutton',
    'sphinx_design',
]

# Intersphinx settings
intersphinx_mapping = {
    'python': ('https://docs.python.org/release/3.6.9', None),
    'numpy': ('https://numpy.org/doc/stable', None),    
}

# Napoleon settings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = True
napoleon_use_param = True
napoleon_use_rtype = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of documents that shouldn't be included in the build.
#unused_docs = []

# List of directories, relative to source directory, that shouldn't be searched
# for source files.
exclude_trees = ['_build']

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

pygments_style = "friendly"
pygments_dark_style = "monokai"


# -- Options for HTML output ---------------------------------------------------

html_theme = 'furo'

html_theme_options = {
    "light_css_variables": {
        "color-brand-primary": "#8C1515",
        "color-brand-content": "#8C1515",
    },
    "dark_css_variables": {
        "color-brand-primary": "#E88E8E",
        "color-brand-content": "#E88E8E",
    },
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
}

html_title = "pysmurf"
html_static_path = ['_static']
html_css_files = ['custom.css']
html_show_sourcelink = True

htmlhelp_basename = 'pysmurfdoc'

# -- Options for LaTeX output --------------------------------------------------

latex_documents = [
    ('index', 'pysmurf.tex', u'pysmurf Documentation',
     u'Edward Young', 'manual'),
]

# Modules to mock up
autodoc_mock_imports = ['pyrogue','smurf','rogue','CryoDet','CryoDevBoard']


# Source code links
def linkcode_resolve(domain, info):
    """
    Determine the URL corresponding to Python object
    """
    if domain != 'py':
        return None

    modname = info['module']
    fullname = info['fullname']

    submod = sys.modules.get(modname)
    if submod is None:
        return None

    obj = submod
    for part in fullname.split('.'):
        try:
            obj = getattr(obj, part)
        except Exception:
            return None

    # strip decorators, which would resolve to the source of the decorator
    try:
        unwrap = inspect.unwrap
    except AttributeError:
        pass
    else:
        obj = unwrap(obj)

    try:
        fn = inspect.getsourcefile(obj)
    except Exception:
        fn = None
    if not fn:
        return None

    try:
        source, lineno = inspect.getsourcelines(obj)
    except Exception:
        lineno = None

    if lineno:
        linespec = "#L%d-L%d" % (lineno, lineno + len(source) - 1)
    else:
        linespec = ""

    fn = relpath(fn, start=dirname(pysmurf_file))
    return "https://github.com/slaclab/pysmurf/blob/%s/python/pysmurf/%s%s" % (
        pysmurf_git_tag, fn, linespec)
